### ISSUE TITLE
err to get the new prompt

### ISSUE THREAD

**Issue by adsian** [corbin-hayden13/SD-Prompt-Enhancer#17]
![image](https://github.com/corbin-hayden13/SD-Prompt-Enhancer/assets/34738478/1a4b2603-2d65-4ca6-bfd1-b23401885eca)
To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 9.0s (import torch: 1.2s, import gradio: 0.7s, import ldm: 0.5s, other imports: 0.9s, load scripts: 2.7s, create ui: 2.3s, gradio launch: 0.6s).
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(4): AS-Young-neg, EasyNegative, FastNegativeEmbedding, yaguru magiku
Model loaded in 4.5s (load weights from disk: 0.5s, create model: 0.7s, apply weights to model: 0.4s, apply half(): 0.5s, move model to device: 1.2s, load textual inversion embeddings: 1.1s).
Traceback (most recent call last):
  File "C:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "C:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\sd-webui-aki-v4.1\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py", line 100, in update_new_prompt
    return update_textbox(new_prompt, *args)
  File "C:\sd-webui-aki-v4.1\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py", line 82, in update_textbox
    value = PromptEnhancerScript.handle_priority(new_prompt, args_list, num_extras)
  File "C:\sd-webui-aki-v4.1\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py", line 315, in handle_priority
    return prompt_priority(prompt, args, all_sections, num_extras)
  File "C:\sd-webui-aki-v4.1\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py", line 21, in prompt_priority
    return "((" + prompt + ")), " + parse_arbitrary_args(args, section_list, num_extras)
  File "C:\sd-webui-aki-v4.1\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py", line 34, in parse_arbitrary_args
    if isinstance(args[b], list) and len(args[b]) > 0:
IndexError: list index out of range

**Comment by corbin-hayden13** [comment]
I accidentally broke main, I pulled a change fixing this issue and you should see regular functionality again
