### ISSUE TITLE
Error executing

### ISSUE THREAD

**Issue by thejohnd0e** [corbin-hayden13/SD-Prompt-Enhancer#27]
```
Error executing callback ui_tabs_callback for D:\stable-diffusion-portable-main\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py
Traceback (most recent call last):
  File "D:\stable-diffusion-portable-main\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "D:\stable-diffusion-portable-main\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py", line 191, in on_ui_tabs
    token_list = sorted(make_token_list(all_sections))
  File "D:\stable-diffusion-portable-main\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py", line 11, in make_token_list
    parse_and_add(ret_list, section.name)
  File "D:\stable-diffusion-portable-main\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py", line 27, in parse_and_add
    words = re.findall(r'\b\w*[a-zA-Z]\w*\b', str_to_parse)
  File "D:\stable-diffusion-portable-main\python\lib\re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

**Comment by thejohnd0e** [comment]
I found the reason for this error is the file brutaltruthlinux929_tags .csv, if I delete this file, the extension starts without errors. So could you check it, please?

**Comment by corbin-hayden13** [comment]
This issue is caused by empty cells in between populated cells in a csv file.  I patched the parsing error but I will continue to develop a method to ignore empty sandwiched cells.
