### ISSUE TITLE
Broken with Autmatic1111 v1.6.0

### ISSUE THREAD

**Issue by SafwanPK** [corbin-hayden13/SD-Prompt-Enhancer#29]
Here is the error from console which breaks this extension from working, when used with latest version of Automatic1111.

*** Error executing callback ui_tabs_callback for C:\Softwares\Graphics\stable-diffusion\stable-diffusion-webui\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py
    Traceback (most recent call last):
      File "C:\Softwares\Graphics\stable-diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Softwares\Graphics\stable-diffusion\stable-diffusion-webui\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py", line 194, in on_ui_tabs
        extra_networks_ui = ui_extra_networks.create_ui(extra_networks_formrow, extra_networks_button,
      File "C:\Softwares\Graphics\stable-diffusion\stable-diffusion-webui\modules\ui_extra_networks.py", line 384, in create_ui
        for tab in unrelated_tabs:
    TypeError: 'ToolButton' object is not iterable

---

**Comment by ShadowPlague21** [comment]
https://chat.openai.com/share/247c847c-52be-4b54-b7ae-fdc3175b8f90

Got some help from ChatGPT

**Comment by RykeWollf** [comment]
having the same issue

> https://chat.openai.com/share/247c847c-52be-4b54-b7ae-fdc3175b8f90
> 
> Got some help from ChatGPT

this link sadly won't work for me, can you help us out if you found the solution?
